Retry when request to whois ip fail.
Ostorlab/agent_whois_ip pull request #29
Opened 2023-11-29 09:39 UTC by mohsinenar

2023-11-29 09:59 UTC, PiranhaSa approved these changes
I think you need to use black

2023-11-29 10:24 UTC, deadly-panda commented on tests/whois_ip_agent_test.py
> +    mocker,
Add the type hint please.

2023-11-29 11:00 UTC, BlueSquare1 submitted a review, later dismissed

2023-11-29 11:00 UTC, BlueSquare1 commented on agent/whois_ip_agent.py
> +                    record = _get_wohis_record(host)
```suggestion
                    record = _get_whois_record(host)
```

2023-11-29 13:24 UTC, elyousfi5 approved these changes

2023-11-30 07:59 UTC, 3asm requested changes

2023-11-30 07:59 UTC, 3asm commented on agent/whois_ip_agent.py
> +WAIT_BETWEEN_RETRY = 3
```suggestion
MAX_RETRY_ATTEMPTS = 2
WAIT_BETWEEN_RETRY = 3
```

2023-11-30 07:59 UTC, 3asm commented on agent/whois_ip_agent.py
> +                    record = _get_whois_record(host)
+1

2023-11-30 07:59 UTC, 3asm commented on tests/whois_ip_agent_test.py
> +    assert mock_request.call_count == 10
Make the assert explicit with 2 * len(scan_message_ipv4_mask)

2023-11-30 10:39 UTC, 3asm approved these changes

2023-11-30 10:39 UTC, merged